### PR TITLE
Timeunits and duration added to TreeDrawer

### PR DESCRIPTION
**Pull request by brtubb-patagonia**
(merging to master this time)

Note: this doesn't include the 'samples' override in the AccumulatedTreeDrawer. Just 'ms' or blank.

Looks like you can accept the PR and squash [via the GitHub UI](https://stackoverflow.com/a/43858707). If you want me to squash it first, cancel the PR and I'll submit a new one!

### CODE REVIEW

**Comment by kornilova-l** [comment]
Could you please leave here only latest commit? I suppose, other changes are already in jfr branch

**Comment by brtubb-patagonia** [comment]
Are you asking to exclude 5d639b2? I'm not sure how to exclude it... I think a rebase would cover it.

Or squash all before the PR?

**Comment by kornilova-l** [comment]
Include only e4ead70bcf92caa5514d86c9a87c41ea3dc67b6c, let it be only about duration

**Comment by brtubb-patagonia** [comment]
Can I include 29d62ae in the new PR? Or in a separate PR? There is a FileOutputStream that needs to be closed before `*.jfr` files can be uploaded. The file is moved later in the code, but the stream isn't close so the move fails.

**Comment by kornilova-l** [comment]
I realised that I lost the 29d62aeb1d4f2b6fc5a9881c41a30a9963ce39d5 in jfr branch during squash and rebase, I've just pushed the fix e27288cc8b9723627622ae1dc78d90c187f74b36 with Kotlin [`use`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html) construction (replacement for try-catch with resource block in Java). So eventually it will be in master :)

**Comment by brtubb-patagonia** [comment]
Thanks for all the help! I submit a new PR to finish this off.

**Pull request closed without merging**
